export const keys = [
  //   "result",
  "phase9",
  "phase8",
  "phase7",
  "phase6",
  "phase5",
  "phase4",
  "phase3",
  "phase2",
  "phase1",
  "index",
];

export const data = [
  {
    index: 0,
    image: "0.png",
    phase1: "hiring manager",
    phase2: "hiring manager",
    phase3: "tech screen",
    phase4: "presentation",
    phase5: "tech interview",
    result: "offer",
    outcome: "I said no",
  },
  {
    index: 1,
    image: "1.png",
    phase1: "recruiter",
    phase2: "hiring manager",
    phase3: "tech screen",
    phase4: "tech interview",
    phase5: "tech interview",
    phase6: "recruiter",
    phase7: "business interview",
    phase8: "business interview",
    phase9: "hiring manager",
    result: "offer",
    outcome: "yes",
  },
  { index: 2, image: "2.png", result: "no response" },
  {
    index: 3,
    image: "3.png",
    phase1: "recruiter",
    phase2: "hiring manager",
    result: "withdrew",
  },
  {
    index: 4,
    image: "4.png",
    phase1: "hiring manager",
    phase2: "hiring manager",
    result: "offer",
    outcome: "I said no",
  },
  {
    index: 5,
    image: "5.png",
    phase1: "recruiter",
    phase2: "homework",
    phase3: "tech interview",
    phase4: "hiring manager",
    phase5: "hiring manager",
    result: "offer",
    outcome: "I said no",
  },
  { index: 6, image: "6.png", result: "no response" },
  {
    index: 7,
    image: "7.png",
    phase1: "hiring manager",
    phase2: "tech interview",
    phase3: "tech interview",
    phase4: "tech interview",
    phase5: "recruiter",
    phase6: "culture interview",
    phase7: "business interview",
    result: "position closed",
  },
  { index: 8, image: "8.png", result: "rejected" },
  {
    index: 9,
    image: "9.png",
    phase1: "recruiter",
    phase2: "hiring manager",
    phase3: "homework",
    result: "rejected",
  },
  { index: 10, image: "10.png", result: "no response" },
  {
    index: 11,
    image: "11.png",
    phase1: "recruiter",
    phase2: "tech screen",
    phase3: "hiring manager",
    result: "withdrew",
  },
  { index: 12, image: "12.png", phase1: "hiring manager", result: "withdrew" },
  { index: 13, image: "13.png", result: "no response" },
  { index: 14, image: "14.png", result: "rejected" },
  { index: 15, image: "15.png", result: "heard back too late" },
  {
    index: 16,
    image: "16.png",
    phase1: "hiring manager",
    phase2: "tech screen",
    phase3: "partner interview",
    result: "ghosted",
  },
];
